// <auto-generated />
namespace Library.Services.Impls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookEdition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookEdition));
        
        string IMigrationMetadata.Id
        {
            get { return "201712161058110_BookEdition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
