// <auto-generated />
namespace Library.Services.Impls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V20171203183722IncomingBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V20171203183722IncomingBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041521098_V20171203183722IncomingBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
